language: node_js

services:
  - docker

node_js:
  - 20 # Use the Node.js version compatible with your project

cache:
  npm: true # Cache npm packages to speed up builds

script: 'true'

jobs:
  include:
    - stage: lint
      if: branch = main
      script:
        - npm run format
        - npm run lint

    - stage: deploy
      script:
        - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.ibm.com/Toby-Keegan/waqqly.git Toby-Keegan/waqqly
        - cd Toby-Keegan/waqqly
        - git status
        - git remote add public_gh https://${PUBLIC_GH_KEY}@github.com/tobykeegan/waqqly.git
        - git push public_gh $TRAVIS_BRANCH
