language: node_js

node_js:
  - 20 # Use the Node.js version compatible with your project

cache:
  npm: true # Cache npm packages to speed up builds

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version

install:
  - bun install # Install project dependencies

jobs:
  include:

    - stage: lint
      if: branch = main
      script:
        - npx playwright install
        - bun run format
        - bun run lint

    - stage: test
      script:
        - npx playwright install
        - bun run test # Run tests (adjust this to match your project setup)

    - stage: build
        - bun run build # Run the build script (adjust this to match your project setup)
