language: node_js

node_js:
  - 20 # Use the Node.js version compatible with your project

cache:
  npm: true # Cache npm packages to speed up builds

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version

install:
  - npx playwright install
  - bun install # Install project dependencies

script:
  - bun run format
  - bun run lint
  - bun run build # Run the build script (adjust this to match your project setup)
  - bun run test # Run tests (adjust this to match your project setup)

deploy:
 provider: azure_web_apps
 on:
   branch: travis-setup