language: node_js

node_js:
  - 20 # Use the Node.js version compatible with your project

cache:
  npm: true # Cache npm packages to speed up builds

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - echo bun --version
  - echo node --version
  - echo npm --version

install:
  - bun install # Install project dependencies

script:
  - bun run lint
  - bun run build # Run the build script (adjust this to match your project setup)
  - bun test # Run tests (adjust this to match your project setup)
