language: node_js

services:
  - docker

node_js:
  - 20 # Use the Node.js version compatible with your project

cache:
  npm: true # Cache npm packages to speed up builds

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version

install:
  - bun install # Install project dependencies

script: 'true'

jobs:
  include:

    - stage: lint
      if: branch = main
      script:
        - npx playwright install
        - bun run format
        - bun run lint

    - stage: test
      script:
        - npx playwright install
        - bun run test # Run tests (adjust this to match your project setup)

    - stage: build
      script:
        - bun run build # Run the build script (adjust this to match your project setup)
        - mv ./Containerfile ./Dockerfile
        - docker build -t waqqly . 
        - docker run -d --name waqqly -p 3000:3000 waqqly
        - docker ps -a

    - stage: deploy_prod
      deploy:
        on:
          all_branches: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: "waqqly"
        skip_cleanup: true
        region: "eu-west-2"
        upload-dir: build