"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { Amplify } from "aws-amplify";
import config from "../aws-exports";
Amplify.configure(config);

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
      ></meta>
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
// export default withAuthenticator(RootLayout);
